name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Package Extension
      run: |
        zip -r leetgfghub-release.zip . -x "*.git*" -x ".github/*" -x "screenshots/*" -x "docs/*"
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./leetgfghub-release.zip
        asset_name: leetgfghub-release.zip
        asset_content_type: application/zip
